### PR TITLE
Hn/update spec2017 results

### PR DESCRIPTION
**Pull request by hnpl**

### CODE REVIEW

**Comment by powerjg** [comment]
Is this for gem5-19 or develop? Also, could you rebase this so it merges cleanly?

Otherwise, it looks good to me!

**Comment by hnpl** [comment]
It's gem5-19 result. I think I should have clarified this somewhere here.

Anyway, should I have more numbers here? E.g. IPC or number of instructions.

**Comment by powerjg** [comment]
It's great as it is. Let's merge it (after rebasing).

However, I'd like to have a set of scripts and a way to easily visualize those other stats as well. But that can be a separate issue/PR.

**Comment by hnpl** [comment]
Abandoned. See #95 for the complete result.

**Pull request closed without merging**
