### PR TITLE
Update SPEC2006 Experiment Results

### PR DESCRIPTION
**Pull request by hnpl**
The results are coming!

### CODE REVIEW

**Review by powerjg — APPROVED** [review]

**Comment by powerjg** [comment]
Great!

**Review by powerjg — APPROVED** [review]

**Comment by hnpl** [comment]
I will merge when all the runs have finished.

**Comment by hnpl** [comment]
squash and merge*

**Comment by hnpl** [comment]
All SimpleTimingCPU runs are complete, so are some of O3CPU runs.

**Comment by hnpl** [comment]
Added a Python notebook showing how to get the table.

**Pull request merged**
