### PR TITLE
Bump version to v1.3.1

### PR DESCRIPTION
**Pull request by powerjg**
@takekoputa and @ayaz91, I want to try to merge this today, but it's blocked on #124 and #125 and possibly hn/docs-mongodb-uri-fix

Let me know if there are any other changes we want to get into this release.

Once this is merged, I'll tag it and we'll update pypi. *Then* we'll be ready to create a gerrit change on googlesource.

### CODE REVIEW

**Review by aakahlow — APPROVED** [review]
Once #124 , #125 and #132 are merged, this can be merged as well. I can't think of any other necessary changes for this release

**Comment by powerjg** [comment]
Great! @takekoputa, it's all in your court :)

**Comment by hnpl** [comment]
I'm working on it

**Comment by hnpl** [comment]
#124 and #132 are ready I think. They need code review, however.
#125 is closed.

**Pull request merged**
