### PR TITLE
fix the order of commands

### PR DESCRIPTION
**Pull request by mabdullahsoyturk**
cd gem5 should be executed before git commit command.

### CODE REVIEW

**Review by powerjg — APPROVED** [review]
lgtm. Thanks for the contribution! Feel free to open an issue if you have any other questions/problems given you're one of the first people outside of UC Davis to use this tool :)

**Review by aakahlow — APPROVED** [review]

**Comment by powerjg** [comment]
@ayaz91, can you merge after the tests pass (or figure out why they are running so slowly)?

**Comment by mabdullahsoyturk** [comment]
@powerjg Thanks for providing this useful tool. Where should I open an issue? Opening an issue is not allowed in this repository.

**Comment by aakahlow** [comment]
> @ayaz91, can you merge after the tests pass (or figure out why they are running so slowly)?

I will merge this once the tests pass (not sure why they are running too slow)

**Comment by mabdullahsoyturk** [comment]
I also fixed the paths in the boot-exit tutorial. Since paths are created according to packer's path, boot-exit.json was failing before the fix.

**Comment by aakahlow** [comment]
Hi @mabdullahsoyturk : Thanks, these paths needed to be updated. Actually, I am currently going through the documentation to make sure that everything is up to date. Expect few more changes by tomorrow!

**Pull request merged**
