### PR TITLE
Update the structure of docs folder (includes updates in paths)

### PR DESCRIPTION
**Pull request by aakahlow**
This PR cleans the docs folder by adding sub folders for groups of related doc files. Paths of the referred pages in .md files are updated as well.

### CODE REVIEW

**Comment by hnpl** [comment]
Is there a way to review this on readthedocs?

**Comment by powerjg** [comment]
I believe so. I think you can enable readthedocs for any branch. @ayaz91, can you do this? Also, can you give me and Hoa permissions on RTD to do this ourselves? My username should be powerjg :)

**Comment by aakahlow** [comment]
I have enabled this branch, should be visible here: 
https://gem5art.readthedocs.io/en/clean-the-docs/index.html

@powerjg : You should be a maintainer on the project. Please, let me know if it is not accessible
@takekoputa : Can you give me your rtd user name?

**Comment by hnpl** [comment]
My readthedocs username is: hoanguyen.

**Comment by aakahlow** [comment]
@takekoputa : done!

**Pull request merged**
