### PR TITLE
Update getruns

### PR DESCRIPTION
**Pull request by powerjg**

### CODE REVIEW

**Comment by powerjg** [comment]
Could I have a quick review of this? Having someone double check is always nice :)

**Review by aakahlow — APPROVED** [review]
Seems good. 

One question: If I am not mistaken, default_db_uri is redundant here, since we have a default in getDBConnection as well. The reason I am asking, is to make sure that launch scripts will still work without passing any uri for the database? Also, does the default uri also need to have a port or by default it uses 27017?

**Comment by powerjg** [comment]
Good point!

I've updated so it's the same default URI.

For the launch scripts, we can do one of 2 things:
1. (The better option) add `db = getDBConnection('mongodb://...')` to the scripts
2. Set the environment variable GEM5ART_DB before running the script

**Review by aakahlow — APPROVED** [review]

**Comment by aakahlow** [comment]
> Good point!
> 
> I've updated so it's the same default URI.
> 
> For the launch scripts, we can do one of 2 things:
> 
> 1. (The better option) add `db = getDBConnection('mongodb://...')` to the scripts
> 2. Set the environment variable GEM5ART_DB before running the script

Sounds good!

**Pull request merged**
