### PR TITLE
First commit. Nothing important really.

### PR DESCRIPTION
**Pull request by mahyarsamani**

### CODE REVIEW

**Comment by powerjg** [comment]
Awesome! Thanks for opening this. Now, just be sure to push here whenever you add something. No need to wait until it works, etc.

**Comment by aakahlow** [comment]
I think it is better if we keep benchmark sources in a different repo!

**Comment by hnpl** [comment]
Does the benchmark work? I'll just check whether the paths in the packer script are correct.

**Comment by mahyarsamani** [comment]
> Does the benchmark work? I'll just check whether the paths in the packer script are correct.

This branch has been moved to another repo. You can find the repo here. The original version of PARSEC has some bugs and typos that need to be fixed. In the repo, you can find the fixed version. 
https://github.com/darchr/parsec-benchmark

**Comment by hnpl** [comment]
Okay, I’ll test it out.

**Comment by powerjg** [comment]
What's the status of this PR? Has it been moved to gem5art-experiments?

**Comment by mahyarsamani** [comment]
Yes!

**Pull request closed without merging**
