### PR TITLE
Remove functions from artifact module

### PR DESCRIPTION
**Pull request by powerjg**
Signed-off-by: Jason Lowe-Power <jason@lowepower.com>

### CODE REVIEW

**Comment by powerjg** [comment]
I'm not sure what the point of these functions was... I don't see them being used anywhere.

I think they really should be functions of the database, if we want to do that. I'm trying to remove as much of the implicit database connections as possible.

**Comment by aakahlow** [comment]
These functions provide a flexible interface to users to search for artifacts of particular type or name in the database and potentially download any associated files. They are referred in the gem5art documentation here: https://gem5art.readthedocs.io/en/latest/main-doc/artifacts.html#searching-the-database

**Comment by powerjg** [comment]
What if instead we required that you passed a db instance into each of these functions.

The problem I'm trying to solve is the reliance on an implicit DB right now

**Comment by powerjg** [comment]
Ok, let me know what you think @ayaz91. I also updated the documentation in this PR

**Review by aakahlow — APPROVED** [review]
Seems all good to me!

**Pull request merged**
