### PR TITLE
Add example of API docs

### PR DESCRIPTION
**Pull request by powerjg**
Signed-off-by: Jason Lowe-Power <jason@lowepower.com>

### CODE REVIEW

**Comment by powerjg** [comment]
BTW, Ayaz: Here's an example of how to use readthedocs to automatically create API docs. See index.rst for the examples. There are a few new requirements to get it to build.

See https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html for details.

Also, there's a way to call the sphinx things from markdown, but I don't remember how. You should put the detailed API documentation at the end of each of the pages on Artifacts/Run/Tasks.

**Comment by powerjg** [comment]
Working on #7

**Comment by powerjg** [comment]
Should we close this PR?

**Comment by powerjg** [comment]
@ayaz91, has this been manually merged? I think that this PR can be closed.

**Comment by aakahlow** [comment]
Yeah, this should be closed now. This other PR is based on this for RTD stuff

**Pull request closed without merging**
