### PR TITLE
Pathlib update

### PR DESCRIPTION
**Pull request by powerjg**
The commits in this PR should be merged at the same time.

I ran the unittests, but I didn't run anything else. @takekoputa, I wasn't 100% on the change to the relative paths in the zips. I tested it manually from the python REPL and I got a zipfile similar to what I think we expect. I see the following when I use one of your results directories. Let me know if this isn't what I should see.

```
$ unzip -l test.zip
Archive:  test.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      829  2019-12-09 13:42   401.bzip2/simout
  1053053  2019-12-09 13:42   401.bzip2/stats.txt
    57366  2019-12-09 13:42   401.bzip2/config.ini
    23039  2019-12-09 13:42   401.bzip2/system.pc.com_1.device
   149623  2019-12-09 13:42   401.bzip2/config.json
        0  2019-12-09 13:42   401.bzip2/speclogs/
   114350  2019-12-09 13:42   401.bzip2/config.dot
    36527  2019-12-09 13:42   401.bzip2/config.dot.pdf
     1555  2019-12-09 13:42   401.bzip2/info.json
     4871  2019-12-09 13:42   401.bzip2/simerr
       83  2019-12-09 13:42   401.bzip2/run_401.bzip2_test
   143626  2019-12-09 13:42   401.bzip2/config.dot.svg
     8618  2019-12-09 13:42   401.bzip2/speclogs/CINT2006.002.test.rsf
    16288  2019-12-09 13:42   401.bzip2/speclogs/CINT2006.002.test.flags.html
  2547358  2019-12-09 13:42   401.bzip2/speclogs/CPU2006.001.log
        4  2019-12-09 13:42   401.bzip2/speclogs/CPU2006.lock
     4129  2019-12-09 13:42   401.bzip2/speclogs/CPU2006.002.log
    62670  2019-12-09 13:42   401.bzip2/speclogs/CINT2006.002.test.pdf
     8385  2019-12-09 13:42   401.bzip2/speclogs/CINT2006.002.test.txt
---------                     -------
  4232374                     19 files

```

### CODE REVIEW

**Comment by hnpl** [comment]
The paths are correct.

**Comment by powerjg** [comment]
Great!

**Comment by powerjg** [comment]
@ayaz91, @takekoputa, @krithi96, @tv-reddy, @mahyarsamani I'd appreciate your reviews on this :). I'd like to have at least two people go through this and approve before it's merged.

The idea in this patch is to use Path instead of strings for all paths *within* gem5art. We'll still allow users of the API to use string to pass paths into gem5art (e.g., via the run object creation), but we'll use pathlib.Path everywhere else.

**Review by aakahlow — APPROVED** [review]

**Comment by aakahlow** [comment]
@powerjg , @takekoputa : There is nothing pending on this PR, right?

**Comment by powerjg** [comment]
I dont think so.

**Comment by hnpl** [comment]
No, I think.

**Comment by aakahlow** [comment]
Ok, I will rebase and merge this!

**Pull request merged**
